### ISSUE TITLE
TypeError: JSON object must be str, bytes or bytearray, not Wrapper

### ISSUE THREAD

**Issue by FuzzyMistborn** [xannor/hass_weather_template#2]
Just updated to 0.118 and am now getting the following error.  I'm guessing it has to do with the template change that was mentioned in the notes, but I'm unsure how to fix.  I made no changes to the config, only difference is the update.  Here is my config:

```
weather:
  - platform: weather_template
    weather:
      combined_weather:
        temperature_template: "{{ states('sensor.acurite_outside_temp') }}"
        temperature_unit_template: "{{ state_attr('sensor.acurite_outside_temp', 'unit_of_measurement') }}"
        humidity_template: "{{ states('sensor.acurite_outside_humidity') }}"
        wind_template: "{{ states('sensor.acurite_outside_windspeed') }}"
        wind_bearing_template: "{{ states('sensor.acurite_outside_wind_direction') }}"
        forecast_template: "{{ state_attr('weather.dining_room', 'forecast') | to_json }}"
```

And the error:

```
Logger: homeassistant.helpers.event
Source: custom_components/weather_template/weather.py:224
First occurred: 1:57:00 PM (2 occurrences)
Last logged: 1:57:30 PM
Error while processing state changed for weather.dining_room

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 257, in _async_state_change_dispatcher
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 434, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 960, in _refresh
    self.hass.async_run_hass_job(self._job, event, updates)
  File "/usr/src/homeassistant/homeassistant/core.py", line 434, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/template/template_entity.py", line 248, in _handle_results
    attr.handle_result(
  File "/usr/src/homeassistant/homeassistant/components/template/template_entity.py", line 87, in handle_result
    self.on_update(result)
  File "/config/custom_components/weather_template/weather.py", line 224, in _update_forecast
    forecast_json = json.loads(forecast)
  File "/usr/local/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not Wrapper

```

**Comment by xannor** [comment]
I haven't upgraded to 118 yet, but from reading the release, I think it means the | to_json is not longer needed. That was to parse the string output, but since the templates now do native by default, you should be able to "pass through" the forecast.

**Comment by FuzzyMistborn** [comment]
I tried taking that out and still didn't have any luck.  I can give it another try here in a bit.

**Comment by xannor** [comment]
I'm in the process of upgrading my HA install so I will see if I get the issue shortly.

**Comment by xannor** [comment]
Fixed in release 1.1

**Comment by FuzzyMistborn** [comment]
Thanks! is |to_json still necessary or no?

**Comment by xannor** [comment]
I took it out of mine for testing and it works without it, so no I do not think it is necessary anymore.
