### ISSUE TITLE
missing 1 required positional argument: 'hass'

### ISSUE THREAD

**Issue by FuzzyMistborn** [xannor/hass_weather_template#4]
Just updated to 2022.02 and getting this in my log:

```
Logger: homeassistant.components.weather
Source: custom_components/weather_template/weather.py:177
Integration: Weather (documentation, issues)
First occurred: 9:29:18 PM (1 occurrences)
Last logged: 9:29:18 PM

Error while setting up weather_template platform for weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/weather_template/weather.py", line 149, in async_setup_platform
    async_add_entities(await _async_create_entities(hass, config))
  File "/config/custom_components/weather_template/weather.py", line 120, in _async_create_entities
    WeatherTemplate(
  File "/config/custom_components/weather_template/weather.py", line 177, in __init__
    super().__init__(availability_template=availability_template)
TypeError: __init__() missing 1 required positional argument: 'hass'

```

**Comment by xannor** [comment]
I haven't been using this anymore since home assistant now has a decent weather template. I would recommend using that instead.

**Comment by FuzzyMistborn** [comment]
Yep I found that. Works just the same.
